receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  filelog:
    include: [/app/vllm_logs.log]
    start_at: beginning
  httpcheck:
    targets:
      - endpoint: http://localhost:8000/health
        method: GET
    collection_interval: 60s

  prometheus:
    config:
      scrape_configs:
        - job_name: opentelemetry-collector
          scrape_interval: 10s
          static_configs:
            - targets: [ 'localhost:8000' ]
          metrics_path: /metrics

exporters:
  otlphttp:
    traces_endpoint: ${env:OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:-http://127.0.0.1:14358/v1/traces}
    metrics_endpoint: ${env:OTEL_EXPORTER_OTLP_METRICS_ENDPOINT:-http://127.0.0.1:14358/v1/metrics}
    logs_endpoint: ${env:OTEL_EXPORTER_OTLP_LOGS_ENDPOINT:-http://127.0.0.1:14358/v1/logs}

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  metricstransform:
    transforms: []
  logstransform:
    transforms: []

service:
  telemetry:
    logs:
      level: INFO
  pipelines:
    metrics:
      receivers: [otlp,prometheus]
      processors: [batch, metricstransform]
      exporters: [otlphttp]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
    logs:
      receivers: [otlp, filelog]
      processors: [batch, logstransform]
      exporters: [otlphttp]